name: wonderart
favicon: null
layout_spectrum: 0.9593797486741096
typography_spectrum: 0.4354241034016013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6980505106039345
  lightness: 0.8499249387532473
  saturation: 0.15138595225289464
  rhythmicContrast: 0.659341957885772
purpose: []
